services:
  postgres:
    container_name: postegres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - book-social-network
    restart: unless-stopped
  pgadmin4:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rgaieghoussem12@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8085
    ports:
      - '127.0.0.1:8085:8085'
    networks:
      - book-social-network
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  book-social-network:
    driver: bridge

volumes:
  postgres:
    driver: local
